const IMAGES = {
  Logo: require("./images/logo.png"),
  Bg: require("./images/Bg.png"),
  Img1: require("./images/img1.jpg"),
  Img2: require("./images/img2.png"),
  Img3: require("./images/img3.png"),
  Img4: require("./images/img4.png"),
  Img5: require("./images/img5.png"),
  Img6: require("./images/img6.png"),
  Img7: require("./images/img7.png"),
  Img8: require("./images/img8.png"),
  Img9: require("./images/img9.png"),
  Img10: require("./images/img10.png"),
  Img11: require("./images/img11.png"),
  Img12: require("./images/img12.png"),
  Img13: require("./images/img13.png"),
  Img14: require("./images/img14.png"),
  Img15: require("./images/img15.png"),
  Img16: require("./images/img16.png"),
  Img17: require("./images/img17.png"),
  Img18: require("./images/img18.png"),
  Img19: require("./images/img19.png"),
  Img20: require("./images/img20.svg"),
  Img21: require("./images/img21.svg"),
  Img22: require("./images/img22.svg"),
  Img23: require("./images/img23.png"),
  Img24: require("./images/img24.png"),
  Img25: require("./images/img25.png"),
  Img26: require("./images/img26.png"),
  Img27: require("./images/img27.png"),
  Img28: require("./images/img28.png"),
  Img29: require("./images/img29.png"),
  Img30: require("./images/img30.png"),
  Img31: require("./images/img31.png"),
  Img32: require("./images/img32.png"),
  Img33: require("./images/img33.png"),
  Img34: require("./images/img34.png"),
  Img35: require("./images/img35.svg").default,
  Img36: require("./images/img36.svg").default,
  Img37: require("./images/img37.png"),
  Img38: require("./images/img38.png"),
};

export default IMAGES;
